#!/usr/bin/env python3
"""registry.py - the studio's record of every pour so far, and a non-binding view of the whole menu.

Usage:
  registry.py                 print both
  registry.py --write         write pours/_studio/registry.md and pours/_studio/menu-assessment.md
  registry.py --out DIR       write both into DIR instead

The registry exists so that names, taglines, epigraphs and motifs never repeat across the 132 pours.
The menu assessment is for Robin to read. It must NEVER steer a drink: the persona comes first, always.
"""
import os, sys
from collections import Counter
import pourfile
from _common import POURS, STUDIO, load_spec, SpecError, resolve
from lint_pour import find_spec
from balance import analyse

TOTAL = 132
FLOOR_NOW, FLOOR_LAUNCH = 3, 12   # spine AD-4: >=3 veto-free always; STRICT_STORE launch: all 132 and >=12 veto-free


def gather():
    rows = []
    for f in pourfile.all_pours(POURS):
        d = pourfile.parse(f)
        r = {"pairing": d["pairing"], "personality": d["personality"], "name": d["name"], "tagline": d["tagline"],
             "epigraph": d["epigraph"], "closing": d["closingLine"], "glass": d["glassware"], "contains": d["contains"] or [],
             "status": (d["status"] or "?").split()[0], "serves": d["serves"] or "1", "family": "?", "style": "?",
             "base": "?", "abv": None, "anchor_kinds": [a["kind"] for a in d["anchors"]]}
        sp = find_spec(d["pairing"])
        if sp:
            spec = load_spec(sp)
            r["family"], r["style"] = spec.get("family", "?"), spec.get("style", "?")
            r["glass"] = spec.get("glass", r["glass"])
            try:
                lines = [l for l in resolve(spec) if l["kind"] != "garnish"]
                spirits = [l for l in lines if l["ml"] and l["ethanol_ml"] / l["ml"] >= 0.30 and l["ml"] > 5]
                r["base"] = max(spirits or lines, key=lambda l: l["ethanol_ml"])["name"]
                r["glass"] = spec.get("glass", r["glass"])
                r["abv"] = analyse(spec)["final"]["abv"]
            except (SpecError, ValueError) as e:
                r["base"] = "? (blocked: %s)" % str(e).split(".")[0]
        rows.append(r)
    return rows


def registry_md(rows):
    out = ["# Pour registry", "", "Generated by `registry.py`. Every pour so far: names, taglines, epigraphs and closing lines "
           "must stay unique, and motifs must not repeat (`lint_pour.py` checks both).", "",
           "| pairing | personality | status | name | tagline | epigraph | closing line | family | base | glass | contains |",
           "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for r in rows:
        out.append("| %s |" % " | ".join(str(x) for x in (r["pairing"], r["personality"], r["status"], r["name"], r["tagline"], r["epigraph"],
                                                           r["closing"], r["family"], r["base"], r["glass"], ", ".join(r["contains"]) or "veto-free")))
    return "\n".join(out) + "\n"


def menu_md(rows):
    n = len(rows)
    approved = sum(r["status"] == "approved" for r in rows)
    vf = sum(not r["contains"] for r in rows if r["status"] == "approved")
    def tally(key):
        c = Counter(r[key] for r in rows)
        return ", ".join("%s %d" % (k, v) for k, v in c.most_common())
    abvs = [r["abv"] for r in rows if r["abv"] is not None]
    out = ["# Menu assessment (non-binding)", "",
           "> For Robin to read. **This view must never steer a drink.** The persona comes first, always.", "",
           "- **Progress:** %d of %d authored, %d approved." % (n, TOTAL, approved),
           "- **Veto-free approved pours:** %d. The floor is %d now (spine AD-4) and %d at launch. %s" % (
               vf, FLOOR_NOW, FLOOR_LAUNCH, "Floor met." if vf >= FLOOR_NOW else "Floor NOT met."),
           "- **Codex families:** %s" % tally("family"),
           "- **Styles:** %s" % tally("style"),
           "- **Base spirits:** %s" % tally("base"),
           "- **Glassware:** %s" % tally("glass"),
           "- **Shared drinks (serves > 1):** %d" % sum(str(r["serves"]).split()[0] not in ("1", "None") for r in rows),
           "- **Strength range (finished ABV):** %s" % ("%.1f%% to %.1f%%" % (min(abvs), max(abvs)) if abvs else "n/a"),
           "- **Anchor kinds used:** %s" % ", ".join("%s %d" % kv for kv in Counter(k for r in rows for k in r["anchor_kinds"]).most_common()),
           ""]
    return "\n".join(out)


def main(argv):
    if len(argv) > 1 and argv[1] in ("-h", "--help"):
        print(__doc__)
        return 0
    rows = gather()
    reg, menu = registry_md(rows), menu_md(rows)
    target = argv[argv.index("--out") + 1] if "--out" in argv else (STUDIO if "--write" in argv else None)
    if target:
        os.makedirs(target, exist_ok=True)
        open(os.path.join(target, "registry.md"), "w").write(reg)
        open(os.path.join(target, "menu-assessment.md"), "w").write(menu)
        print("wrote registry.md and menu-assessment.md to", target)
    else:
        print(reg)
        print(menu)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
