"""Render reachability-v1.json + distribution-v1.json as the reviewable markdown reports.

  python3 render.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def witness_line(w):
    if not w:
        return "—"
    g = ", ".join(f"{k.split('-')[0]}{'→' if v >= 50 else '←'}{v}" for k, v in w["gravity"].items())
    t = " ".join(f"{k}:{v}" for k, v in w["texture"].items()) or "none"
    parts = [
        "drawn " + "/".join(w["drawnToward"]) if w["drawnToward"] else "drawn —",
        "sought " + "/".join(w["soughtFor"]) if w["soughtFor"] else "sought —",
        f"H4 {t}",
        f"H3 {g}",
    ]
    if w.get("flavors"):
        parts.append("flav " + "/".join(w["flavors"]))
    if w.get("vetoes"):
        parts.append("veto " + "/".join(w["vetoes"]))
    return "; ".join(parts)


def reach():
    rows = json.load(open(os.path.join(HERE, "reachability-v1.json")))
    lead = sum(r["leads_fallback"] == "persona alone" for r in rows)
    out = [
        "# Reachability report — matching model v1 (2026-10-06)",
        "",
        "Generated by `analyze.py` + `render.py` from `model-v1.json`, the 132 dossiers' `contains` and the specs' flavour profile. Rerun both after any change to weights, vocabulary or catalogue.",
        "",
        "**Method.** Exact search (mixed-integer programme, scipy/HiGHS) over the whole v3 answer space: H5 ≤3 words per round, H4 each pair a/b/none, H3 any lean, ≤3 flavours. For each pairing it maximises the smallest margin by which that pairing beats all 131 others. A positive optimum gives a witness answer set, re-checked through the reference selector with integer sliders. A non-positive optimum would prove the pairing cannot lead. Vetoes are tried only when the persona alone cannot lead.",
        "",
        "**Layers.**",
        "1. *Leads the fallback.* The pairing is `shortlist[0]`, which is what the guest gets when the Bartender fails or returns an invalid pick.",
        "2. *Enters the shortlist.* The pairing is in the top 3 eligible pairings. Leading implies this.",
        "3. *Final choice.* By protocol the Bartender may pick any shortlisted pairing (AD-3/AD-6), so a shortlisted pairing is *selectable*. Whether the Bartender actually picks it has **not** been observed. That needs reviewed Bartender fixtures (ticket in the build plan), and a deterministic fixture never proves how often the LLM chooses it.",
        "",
        f"**Result.** {lead}/132 pairings can lead the fallback on persona answers alone, with no vetoes and no flavour help. 132/132 can enter the shortlist. 0 are proven unreachable and 0 are unproven. Final choice: 132 are selectable and 0 have been observed. The witnesses are saved as `fixtures-v1.json`, one answer set per pairing, for the core's coverage tests.",
        "",
        "**Margin** is the best-case lead in score units, for reference: the median top-1 margin under uniform answers is about 0.38. Small best-case margins show where the evidence is thin: ruler-explorer, ruler-magician, ruler-outlaw, sage-explorer and sage-magician are reachable but rare (see distribution-v1.md).",
        "",
        "| # | pairing | status | contains | leads fallback | best margin | shortlist | final choice | witness (one answer set that makes it lead) |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for i, r in enumerate(rows, 1):
        c = ", ".join(r["contains"]) if r["contains"] else "—"
        out.append(f"| {i} | {r['key']} | {r['status']} | {c} | {r['leads_fallback']} | {r['persona_margin']} | {r['shortlist']} | selectable · not observed | {witness_line(r['witness'])} |")
    open(os.path.join(HERE, "reachability-v1.md"), "w").write("\n".join(out) + "\n")


def dist():
    d = json.load(open(os.path.join(HERE, "distribution-v1.json")))
    models = [k for k in d if isinstance(d[k], dict) and "samples" in d[k]]
    keys = [
        ("distinct_outcomes", "distinct top-1 outcomes (of 132)"),
        ("max_share", "largest single-outcome share (uniform = 0.0076)"),
        ("top10_share", "share of the 10 most common outcomes"),
        ("exact_tie_rate", "exact top-1/top-2 ties"),
        ("near_tie_rate_lt_0.05", "near ties (margin < 0.05)"),
        ("median_top1_margin", "median top-1 margin"),
        ("one_answer_changes_top1", "one changed answer changes the top-1"),
        ("one_answer_changes_primary", "one changed answer changes the primary"),
        ("after_one_change_top1_was_in_old_shortlist", "after one change, new top-1 was in the old shortlist"),
    ]
    out = [
        "# Distribution and sensitivity — matching model v1 (2026-10-06)",
        "",
        "These figures describe the **model under stated answer assumptions, not the real audience**. Compare them with playtests later. Equal outcome frequencies are not the goal. The aim is that no persona is starved of evidence and no question group dominates.",
        "",
        "**Answer models** (seeded simulation, 6,000 samples each):",
        "- **U uniform:** every option is equally likely; 1–3 words per H5 round; each H4 pair is a, b or missed (45/45/10%); H3 uniform 0–100; 0–3 flavours.",
        "- **H hesitant:** H3 clusters near the middle (normal, mean 50, sd 18); 1–2 words per round; 30% of H4 pairs missed; 0–2 flavours.",
        "- **C coherent:** a hidden pairing answers in character, with options drawn in proportion to exp(2 × affinity to primary + 0.7 × affinity to secondary). This is **circular**: it uses the model's own affinities, so it measures whether a persona that answers as the weights assume comes back. It does not measure whether people really answer that way.",
        "",
        "| metric | " + " | ".join(models) + " |",
        "| --- | " + " | ".join("---" for _ in models) + " |",
    ]
    for k, label in keys:
        out.append(f"| {label} | " + " | ".join(str(d[m][k]) for m in models) + " |")
    out += ["", "**Primary share by archetype** (expected if even: 0.083)", "", "| archetype | " + " | ".join(models) + " |", "| --- | " + " | ".join("---" for _ in models) + " |"]
    for a in d[models[0]]["primary_shares"]:
        out.append(f"| {a} | " + " | ".join(str(d[m]["primary_shares"][a]) for m in models) + " |")
    c = d[models[2]]
    out += [
        "",
        f"**Recovery under C:** exact pairing {c['latent_recovered_top1']}, in the shortlist {c['latent_recovered_in_shortlist']}, reversed pair served instead {c['reversed_pair_instead']}. Chance would be 0.0076, 0.023 and 0.0076.",
        "",
        "| latent primary | primary recovered |",
        "| --- | --- |",
    ]
    out += [f"| {a} | {v} |" for a, v in c["primary_recovery_by_latent_primary"].items()]
    out += ["", "**Group influence:** how often removing one group changes the top-1.", "", "| group | " + " | ".join(models) + " |", "| --- | " + " | ".join("---" for _ in models) + " |"]
    for g in d[models[0]]["dropping_group_changes_top1"]:
        out.append(f"| {g} | " + " | ".join(str(d[m]["dropping_group_changes_top1"][g]) for m in models) + " |")
    out += [
        "",
        f"**Flavour weight φ** (current 0.15), under U: share of top-1 results that change against the current φ: {d['flavour_weight_change_vs_current']}.",
        "",
        f"**Vetoes**, under U: share of top-1 results that change when the veto is set: {d['veto_changes_top1']}. Twenty pours contain nuts, which is why the nuts veto moves results most.",
        "",
        f"**Empty intake** (no answers at all): every score is 0, so the result is decided by the pairingKey tie-break: {d['empty_intake']}. The journey cannot normally produce this, because H3 always commits a value.",
        "",
        "**Never observed in any sample, but proven reachable** (see reachability-v1.md): " + ", ".join(sorted(set(sum((d[m]["never_observed"] for m in models), [])))) + ".",
        "",
        "## Reading",
        "",
        "1. **No ties, no dead outcomes.** Exact ties do not occur with continuous H3 values, and near ties stay under 9%. Every pairing is reachable.",
        "2. **The thin-evidence skew is real and traced.** Caregiver, Creator, Ruler and Sage come out as primary 2–5% of the time, against about 11% for the rest. Even a guest answering in character as one of them gets that primary back only 10–22% of the time. The cause is the drawnToward question (*What are you most drawn toward?*): it has no word whose core is their goal (Service, Innovation, Control, Wisdom). The 2026-09-18 trims removed Knowledge, Power and Recognition as overlaps. Adding weight to soughtFor instead (variant A) barely helps: Caregiver goes 0.08 → 0.12 and Ruler 0.19 → 0.16. The question edit (variant Q12, matching-model.md §Recommended question edit) evens primary shares to 0.05–0.10 and lifts their recovery to 0.30–0.47.",
        "3. **Reversed pairs are the hard distinction.** Under C, the reversed pair is served about as often as the right one. This is built in: the primary and secondary of a coherent guest pull on the same answers, and only the split between drawnToward (motive) and everything else (expression) tells them apart. The shortlist softens it: about a third of the time the right pairing is in the Bartender's three. Playtests should check whether guests feel the difference.",
        "4. **Sensitivity is high per pairing and moderate per primary.** Changing one answer changes the exact pairing about half the time, and the primary about 30% of the time. In about 74% of cases the new result was already in the old shortlist. 132 fine outcomes from about 25 answers are expected to sit close together. This is acceptable as long as the shortlist absorbs most single-answer changes.",
        "5. **Group balance holds.** The two H5 questions lead, as designed. H3 and H4 each still change about 40% of results. Flavour changes about 4–5% (a nudge, as designed), and so do single vetoes, except nuts.",
    ]
    open(os.path.join(HERE, "distribution-v1.md"), "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    reach()
    dist()
