"""Render reachability-v1.json + distribution-v1.json as the reviewable markdown reports.

  python3 render.py
"""

import hashlib
import json
import os

import matching as mt

HERE = os.path.dirname(os.path.abspath(__file__))


def analysis():
    with open(os.path.join(HERE, "distribution-v1.json")) as source:
        data = json.load(source)
    meta = data["_analysis"]
    for name, path in (("model", mt.MODEL_PATH), ("scales", mt.SCALES_PATH), ("catalogue", mt.CATALOGUE_PATH)):
        with open(path, "rb") as source:
            current = hashlib.sha256(source.read()).hexdigest()
        if meta["source_hashes"].get(name) != current:
            raise ValueError(f"stale analysis input: {name}; rerun analyze.py")
    if meta["reachability_regenerated"]:
        for name in ("reachability-v1.json", "fixtures-v1.json"):
            with open(os.path.join(HERE, name), "rb") as source:
                current = hashlib.sha256(source.read()).hexdigest()
            if meta.get("output_hashes", {}).get(name) != current:
                raise ValueError(f"stale analysis output: {name}; rerun analyze.py")
    return data


def witness_line(w):
    if not w:
        return "—"
    g = ", ".join(f"{k.split('-')[0]}{'→' if v >= 50 else '←'}{v}" for k, v in w["gravity"].items())
    t = " ".join(f"{k}:{v}" for k, v in w["texture"].items()) or "none"
    parts = [
        "drawn " + "/".join(w["drawnToward"]) if w["drawnToward"] else "drawn —",
        "sought " + "/".join(w["soughtFor"]) if w["soughtFor"] else "sought —",
        f"H4 {t}",
        f"H3 {g}",
    ]
    if w.get("flavors"):
        parts.append("flav " + "/".join(w["flavors"]))
    if w.get("vetoes"):
        parts.append("veto " + "/".join(w["vetoes"]))
    return "; ".join(parts)


def reach():
    data = analysis()
    meta = data["_analysis"]
    if not meta["reachability_regenerated"]:
        raise ValueError("reachability evidence was not regenerated; run analyze.py without --skip-reach")
    with open(os.path.join(HERE, "reachability-v1.json")) as source:
        rows = json.load(source)
    lead = sum(r["leads_fallback"] == "persona alone" for r in rows)
    shortlisted = sum(r["shortlist"].startswith("reachable") for r in rows)
    out = [
        f"# Reachability report — matching model v1 ({meta['date']})",
        "",
        "Generated by `analyze.py` + `render.py` from the model, shipped scales and validated catalogue in `../../dionysus-experience/shared/`. Rerun both and export the Python reference after any change to weights, vocabulary or catalogue.",
        "",
        f"**Catalogue.** {meta['authored']} authored pours, {meta['veto_free']} veto-free. Shipped scales were read unchanged; analysis did not recalibrate them.",
        "",
        "**Method.** Exact search (mixed-integer programme, scipy/HiGHS) over the whole v3 answer space: H5 ≤3 words per round, H4 each pair a/b/none, H3 any lean, ≤3 flavours. For each pairing it maximises the smallest margin by which that pairing beats all 131 others. A positive optimum gives a witness answer set, re-checked through the reference selector with integer sliders. A non-positive optimum would prove the pairing cannot lead. Vetoes are tried only when the persona alone cannot lead.",
        "",
        "**Layers.**",
        "1. *Leads the fallback.* The pairing is `shortlist[0]`, which is what the guest gets when the Bartender fails or returns an invalid pick.",
        "2. *Enters the shortlist.* The pairing is in the top 3 eligible pairings. Leading implies this.",
        "3. *Final choice.* By protocol the Bartender may pick any shortlisted pairing (AD-3/AD-6), so a shortlisted pairing is *selectable*. Whether the Bartender actually picks it has **not** been observed. That needs reviewed Bartender fixtures (ticket in the build plan), and a deterministic fixture never proves how often the LLM chooses it.",
        "",
        f"**Result.** {lead}/{len(rows)} pairings can lead the fallback on persona answers alone, with no vetoes and no flavour help. {shortlisted}/{len(rows)} can enter the shortlist. Final choice: {shortlisted} are selectable; the live Bartender has not been observed. Witnesses are saved in `fixtures-v1.json` and exported into the core's Python parity corpus.",
        "",
        f"**Margin** is the best-case lead in score units. The median top-1 margin under uniform answers is {data['U uniform']['median_top1_margin']}; see distribution-v1.md for model frequency assumptions.",
        "",
        "| # | pairing | status | contains | leads fallback | best margin | shortlist | final choice | witness answer set |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for i, r in enumerate(rows, 1):
        c = ", ".join(r["contains"]) if r["contains"] else "—"
        out.append(f"| {i} | {r['key']} | {r['status']} | {c} | {r['leads_fallback']} | {r['persona_margin']} | {r['shortlist']} | {r['final_choice']} | {witness_line(r['witness'])} |")
    open(os.path.join(HERE, "reachability-v1.md"), "w").write("\n".join(out) + "\n")


def dist():
    d = analysis()
    meta = d["_analysis"]
    models = [k for k in d if isinstance(d[k], dict) and "distinct_outcomes" in d[k]]
    keys = [
        ("distinct_outcomes", "distinct top-1 outcomes (of 132)"),
        ("max_share", "largest single-outcome share (uniform = 0.0076)"),
        ("top10_share", "share of the 10 most common outcomes"),
        ("exact_tie_rate", "exact top-1/top-2 ties"),
        ("near_tie_rate_lt_0.05", "near ties (margin < 0.05)"),
        ("median_top1_margin", "median top-1 margin"),
        ("one_answer_changes_top1", "one changed answer changes the top-1"),
        ("one_answer_changes_primary", "one changed answer changes the primary"),
        ("after_one_change_top1_was_in_old_shortlist", "after one change, new top-1 was in the old shortlist"),
    ]
    out = [
        f"# Distribution and sensitivity — matching model v1 ({meta['date']})",
        "",
        "These figures describe the **model under stated answer assumptions, not the real audience**. Compare them with playtests later. Equal outcome frequencies are not the goal. The aim is that no persona is starved of evidence and no question group dominates.",
        "",
        f"**Answer models** (seeded simulation, {meta['samples']:,} samples each; {meta['authored']} authored, {meta['veto_free']} veto-free):",
        "- **U uniform:** every option is equally likely; 1–3 words per H5 round; each H4 pair is a, b or missed (45/45/10%); H3 uniform 0–100; 0–3 flavours.",
        "- **H hesitant:** H3 clusters near the middle (normal, mean 50, sd 18); the uniform sample's H5 words are truncated to at most two and flavours to at most two; 37% of H4 pairs are missed in expectation (10% initially absent, then 30% of the remaining 90% removed).",
        "- **C coherent:** a hidden pairing answers in character, with word options drawn in proportion to exp(2 × (affinity to primary + 0.7 × affinity to secondary)). This is **circular**: it uses the model's own affinities, so it measures whether a persona that answers as the weights assume comes back. It does not measure whether people really answer that way.",
        "",
        "| metric | " + " | ".join(models) + " |",
        "| --- | " + " | ".join("---" for _ in models) + " |",
    ]
    for k, label in keys:
        out.append(f"| {label} | " + " | ".join(str(d[m][k]) for m in models) + " |")
    out += ["", "**Primary share by archetype** (expected if even: 0.083)", "", "| archetype | " + " | ".join(models) + " |", "| --- | " + " | ".join("---" for _ in models) + " |"]
    for a in d[models[0]]["primary_shares"]:
        out.append(f"| {a} | " + " | ".join(str(d[m]["primary_shares"][a]) for m in models) + " |")
    c = d[models[2]]
    out += [
        "",
        f"**Recovery under C:** exact pairing {c['latent_recovered_top1']}, in the shortlist {c['latent_recovered_in_shortlist']}, reversed pair served instead {c['reversed_pair_instead']}. Chance would be 0.0076, 0.023 and 0.0076.",
        "",
        "| latent primary | primary recovered |",
        "| --- | --- |",
    ]
    out += [f"| {a} | {v} |" for a, v in c["primary_recovery_by_latent_primary"].items()]
    out += ["", "**Group influence:** how often removing one group changes the top-1.", "", "| group | " + " | ".join(models) + " |", "| --- | " + " | ".join("---" for _ in models) + " |"]
    for g in d[models[0]]["dropping_group_changes_top1"]:
        out.append(f"| {g} | " + " | ".join(str(d[m]["dropping_group_changes_top1"][g]) for m in models) + " |")
    out += [
        "",
        f"**Flavour weight φ** (current {meta['phi']}), under U: share of top-1 results that change against the current φ: {d['flavour_weight_change_vs_current']}.",
        "",
        f"**Vetoes**, under U: share of top-1 results that change when the veto is set: {d['veto_changes_top1']}. Current contains counts: {meta['veto_counts']}.",
        "",
        f"**Empty intake** (no answers at all): every score is 0, so the result is decided by the pairingKey tie-break: {d['empty_intake']}. The journey cannot normally produce this, because H3 always commits a value.",
        "",
        "**Never observed in any of these answer models** (compare reachability-v1.md): " + (", ".join(sorted(set.intersection(*(set(d[m]["never_observed"]) for m in models)))) or "none") + ".",
        "",
        "## Reading",
        "",
        f"1. **Observed ties are model results.** Uniform exact-tie rate: {d['U uniform']['exact_tie_rate']}; near-tie rate: {d['U uniform']['near_tie_rate_lt_0.05']}. The deterministic key rule still handles ties and an empty intake.",
        "2. **Evidence is more even since Q12.** The twelve-word round gives every archetype a direct motive word; Outlaw, which lost Mischief, is now the thinnest primary. The tables quantify this model's skew; matching-model.md records the edit.",
        f"3. **Reversed pairs remain difficult.** Under C, exact recovery is {c['latent_recovered_top1']}, reversed recovery {c['reversed_pair_instead']}, and shortlist recovery {c['latent_recovered_in_shortlist']}. These are circular simulation results, not guest validation.",
        f"4. **Single-answer sensitivity.** Under U, one edit changes the pairing {d['U uniform']['one_answer_changes_top1']} of the time and the primary {d['U uniform']['one_answer_changes_primary']}; the new pairing was in the old shortlist {d['U uniform']['after_one_change_top1_was_in_old_shortlist']} of the time.",
        "5. **Group balance.** The ablation table reports each group's effect. Missing groups stay neutral; the remaining roles are never renormalized. Shipped scales remain fixed during regeneration.",
    ]
    open(os.path.join(HERE, "distribution-v1.md"), "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    reach()
    dist()
