// Byte-stable renderings of the import's outputs: sorted keys, 2-space
// JSON, a trailing newline, no timestamps.

import type { PairingKey } from '../pairing.ts';

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
    return Object.fromEntries(entries.map(([k, v]) => [k, sortKeys(v)]));
  }
  return value;
}

export const stableJson = (value: unknown): string => `${JSON.stringify(sortKeys(value), null, 2)}\n`;

// shared/data/pours/index.ts: one lazy loader per imported pour, so the
// copy stays out of the first bundle and shared/ never needs node:fs.
export function loadersModule(pairings: readonly PairingKey[]): string {
  const rows = pairings.map((p) => `  '${p}': pour(() => import('./${p}.json')),`);
  return [
    '// GENERATED by scripts/import-pours.ts. Do not edit; run `npm run import:pours`.',
    '//',
    '// One lazy loader per authored pour. The JSON is validated in the build by',
    '// shared/data/catalogue.test.ts (shared/validate.ts).',
    '',
    "import type { PairingKey } from '../../pairing';",
    "import type { AuthoredPour } from '../schema';",
    '',
    'export type PourLoader = () => Promise<AuthoredPour>;',
    '',
    'const pour =',
    '  (load: () => Promise<{ default: unknown }>): PourLoader =>',
    '  async () =>',
    '    (await load()).default as AuthoredPour;',
    '',
    '// Partial: the `PairingKey` type also admits self-pairings (hero-hero),',
    '// which never exist, and a development store may hold fewer than 132.',
    '// The validator checks coverage (all 132 under STRICT_STORE=1).',
    'export const POUR_LOADERS: Partial<Record<PairingKey, PourLoader>> = {',
    ...rows,
    '};',
    '',
  ].join('\n');
}

// A separate static registry supports synchronous reading assembly without
// changing lazy callers. Only imported keys exist in a development store.
export function staticModule(pairings: readonly PairingKey[]): string {
  const keys = [...pairings].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  return [
    '// GENERATED by scripts/import-pours.ts. Do not edit; run `npm run import:pours`.',
    '// Synchronous authored store for shared/reading.ts; validated in the build.',
    '',
    "import type { PairingKey } from '../../pairing';",
    "import type { AuthoredPour } from '../schema';",
    ...keys.map((p, i) => `import pour${i} from './${p}.json';`),
    '',
    '// Partial: self-pairings never exist; a development store may be sparse.',
    'export const AUTHORED_POURS: Partial<Record<PairingKey, AuthoredPour>> = {',
    ...keys.map((p, i) => `  '${p}': pour${i} as AuthoredPour,`),
    '};',
    '',
  ].join('\n');
}

export type ReportInput = {
  pairings: readonly PairingKey[];
  statuses: ReadonlyMap<PairingKey, string>;
  warnings: ReadonlyMap<PairingKey, readonly string[]>;
  vetoFree: number;
};

const DECISION = (w: string) => w.startsWith('trailing closing line');

const CATEGORIES: [string, (w: string) => boolean][] = [
  ['Needs a decision (Robin or content owner)', DECISION],
  ['Excluded trailing reading material', (w) => w.startsWith('excluded trailing')],
  ['Duplicate **yours** heading (ignored)', (w) => w.startsWith('duplicate **yours**')],
  ['Duplicate labels', (w) => w.startsWith('duplicate label')],
  ['Quantity differences (dossier vs spec)', (w) => w.startsWith('quantity:')],
  ['Quantities not compared', (w) => w.startsWith('not compared:')],
  ['Inline markdown kept verbatim', (w) => w.startsWith('inline markdown')],
  ['Allergens', (w) => w.startsWith('contains declares')],
  ['Text outside the sections (ignored)', (w) => w.startsWith('text before the first section')],
  ['Numbering', (w) => / numbered \d+ after \d+$/.test(w) || w.startsWith('yours has ')],
];

const category = (w: string) => CATEGORIES.find(([, test]) => test(w))?.[0] ?? 'Other';
const flat = (w: string) => w.replace(/\s+/g, ' ');

export function renderReport({ pairings, statuses, warnings, vetoFree }: ReportInput): string {
  const lines: string[] = [
    '# Pour import report',
    '',
    'GENERATED by `scripts/import-pours.ts` (`npm run import:pours` in dionysus-experience). Do not edit.',
    '',
    'Trailing reading material, ignored text and the `## Dossier` section were excluded from the',
    'records. Inline markdown in guest text was kept verbatim and is in the records; how it renders',
    "is the front-end's call. Quantity differences are between the guest's recipe (dossier) and the",
    "Mixologist's spec, whose units legitimately differ; they never fail the import.",
    '',
    `- Pours imported: ${pairings.length}`,
  ];
  const statusCount = new Map<string, number>();
  for (const p of pairings) statusCount.set(statuses.get(p) ?? '?', (statusCount.get(statuses.get(p) ?? '?') ?? 0) + 1);
  lines.push(`- Status: ${['draft', 'flagged', 'approved'].map((s) => `${s} ${statusCount.get(s) ?? 0}`).join(', ')}`);
  lines.push(`- Veto-free (empty \`contains\`): ${vetoFree}`);
  const totals = new Map<string, number>();
  for (const p of pairings) for (const w of warnings.get(p) ?? []) totals.set(category(w), (totals.get(category(w)) ?? 0) + 1);
  for (const [name] of [...CATEGORIES, ['Other']]) {
    if (totals.get(name)) lines.push(`- ${name}: ${totals.get(name)}`);
  }

  lines.push('', '## Needs a decision (Robin or content owner)', '');
  const decisions = pairings.flatMap((p) => (warnings.get(p) ?? []).filter(DECISION).map((w) => `- **${p}** (${statuses.get(p)}): ${flat(w)}`));
  lines.push(...(decisions.length ? decisions : ['None.']));

  const clean = pairings.filter((p) => !(warnings.get(p) ?? []).length);
  lines.push('', `Pours with nothing to report: ${clean.length ? clean.join(', ') : 'none'}.`, '');

  for (const p of pairings) {
    const list = warnings.get(p) ?? [];
    if (!list.length) continue;
    lines.push(`## ${p} (${statuses.get(p)})`, '');
    for (const [name] of [...CATEGORIES, ['Other']]) {
      const items = list.filter((w) => category(w) === name);
      if (!items.length) continue;
      lines.push(`**${name}**`, '');
      for (const item of items) lines.push(`- ${flat(item)}`);
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}
