import re
r=open('psychologist-reading-v3.md').read()
who=r.split('## whoYouAre')[1].split('## yours')[0].strip()
yours=r.split('## yours')[1].split('## Notes for the room')[0].strip()
yours=re.sub(r' \((?:Oxford pdf \d+; )?F\d+(?:, F\d+)*\)','',yours)
anch=open('historian-anchors.md').read()
table='\n'.join(l for l in anch.splitlines() if l.startswith('|'))
kept=anch.split('## Kept out of everything the guest sees')[1].strip()
card=open('../../fact-cards/hanky-panky.md').read()
card_leg=card.split('## Legends')[1].split('## Conflicts')[0].strip()
card_conf=card.split('## Conflicts')[1].strip()
brief=open('mixologist-ritual-and-brief.md').read()
scene=brief.split('## Image brief (SCENE, ready to paste)')[1].split('## Round 6 notes')[0].strip()
checks=open('mixologist-checks.md').read().split('### Checks')[1].strip()
res=open('psychologist-resonance-v1.md').read().split('\n',2)[2].strip()
res=re.sub(r'^## ','#### ',res,flags=re.M)
audit=open('historian-audit-v3.md').read().split('\n',1)[1].strip()
tpl=open('_host/template.md').read()
out=tpl.format(table=table,who=who,yours=yours,checks=checks,audit=audit,res=res,kept=kept,card_leg=card_leg,card_conf=card_conf,scene=scene)
open('_host/provisional.md','w').write(out)
