#!/usr/bin/env python3
"""Collection review 2026-10-06: cross-collection signals from matrix.json -> signals.md.

Flags start an editorial reading; they never trigger a replacement on their own.
Usage: python3 signals.py
"""
import json, re
from collections import Counter, defaultdict
from pathlib import Path

REVIEW = Path(__file__).resolve().parent.parent
m = json.loads((REVIEW / "matrix.json").read_text())


def first_words(s, n=4):
    return " ".join(re.findall(r"[A-Za-z'’]+", s)[:n]).lower()


def last_sentence(s):
    ss = [x for x in re.split(r"(?<=[.!?])\s+", s.strip()) if x]
    return ss[-1] if ss else ""


out = ["# Collection signals (generated)\n",
       "Generated by `tools/signals.py` from `matrix.json` (2026-10-06). Mechanical flags only: each one starts an editorial reading and never triggers a replacement by itself.\n"]

# taglines
flags = Counter(f for r in m.values() for f in r["tagline_flags"])
out.append("## Taglines across all 132\n")
out.append(f"- two short sentences: {flags['two-sentence']} · opens with You: {flags['opens-You']} · opens with a mass word (Everyone/Nobody/People/Most people…): {flags['mass-contrast']} · public/private turn: {flags['public/private']} · not-X-but-Y: {flags['not-X-but-Y']}\n")
lens = Counter(len(re.findall(r"\w+", r["tagline"])) // 4 * 4 for r in m.values())
out.append("- length (words, bucketed by 4): " + ", ".join(f"{k}–{k+3}: {v}" for k, v in sorted(lens.items())) + "\n")
ow = Counter(first_words(r["tagline"], 2) for r in m.values())
out.append("- most common first two words: " + ", ".join(f"“{k}” ×{v}" for k, v in ow.most_common(12)) + "\n")
out.append("\n| pairing | name | tagline | flags |\n| --- | --- | --- | --- |\n" + "".join(
    f"| {k} | *{r['name']}* | {r['tagline']} | {', '.join(r['tagline_flags'])} |\n" for k, r in sorted(m.items())))

# whoYouAre openings and recurrent phrases
out.append("\n## whoYouAre openings (first four words) used more than once\n")
wo = defaultdict(list)
for k, r in m.items():
    wo[first_words(r["whoYouAre"])].append(k)
for w, ks in sorted(wo.items(), key=lambda x: -len(x[1])):
    if len(ks) > 1:
        out.append(f"- “{w}…” ×{len(ks)}: {', '.join(ks)}\n")

# yours 1 openings
out.append("\n## Reading openings (yours 1, first four words) used more than once\n")
yo = defaultdict(list)
for k, r in m.items():
    if r["yours"]:
        yo[first_words(re.sub(r"^\d+\.\s*", "", r["yours"][0]))].append(k)
for w, ks in sorted(yo.items(), key=lambda x: -len(x[1])):
    if len(ks) > 1:
        out.append(f"- “{w}…” ×{len(ks)}: {', '.join(ks)}\n")

# proposal paragraph openings and endings
out.append("\n## Proposal paragraph (last yours) openings used more than once\n")
po = defaultdict(list)
for k, r in m.items():
    if r["yours"]:
        po[first_words(re.sub(r"^\d+\.\s*", "", r["yours"][-1]), 3)].append(k)
for w, ks in sorted(po.items(), key=lambda x: -len(x[1])):
    if len(ks) > 1:
        out.append(f"- “{w}…” ×{len(ks)}: {', '.join(ks)}\n")

PHRASES = {
    "I like to think": r"I like to think",
    "Here's what I'd ask (rationed)": r"Here'?s what I'?d ask",
    "That's you, isn't it? (rationed)": r"That'?s you, isn'?t it",
    "So, a proposal / a proposal": r"\bproposal\b",
    "Next time": r"\bNext time\b",
    "I'd like you to": r"I'?d like you to",
    "I suspect": r"\bI suspect\b",
    "I'd guess": r"\bI'?d guess\b",
    "isn't X. It's Y (in whoYouAre)": None,
    "the one thing": r"\bthe one thing\b",
    "nobody (anywhere in the reading)": r"\b(nobody|no one)\b",
    "everyone (anywhere in the reading)": r"\beveryone\b",
    "quietly / quiet": r"\bquiet(ly)?\b",
}
out.append("\n## Recurring phrases (pours using each, whole guest text)\n\n| phrase | pours | share |\n| --- | --- | --- |\n")
for label, rx in PHRASES.items():
    if rx is None:
        n = sum(1 for r in m.values() if re.search(r"(isn'?t|wasn'?t|never) [^.]{0,40}\. (It'?s|It was|You'?re)", r["whoYouAre"]))
    else:
        n = sum(1 for r in m.values() if re.search(rx, " ".join([r["whoYouAre"]] + r["yours"] + [r["closingLine"]]), re.I))
    out.append(f"| {label} | {n} | {n*100//len(m)}% |\n")

# closing lines starting words
out.append("\n## Closing-line first word\n\n" + ", ".join(f"{k} ×{v}" for k, v in Counter(first_words(r['closingLine'], 1) for r in m.values()).most_common(15)) + "\n")

# fact cards shared by more than one pour
out.append("\n## Fact cards cited by more than one pour (repeated historical anchors)\n")
fc = defaultdict(list)
for k, r in m.items():
    for c in r["fact_cards"]:
        fc[c].append(k)
for c, ks in sorted(fc.items(), key=lambda x: -len(x[1])):
    if len(ks) > 1:
        out.append(f"- `{c}` ×{len(ks)}: {', '.join(ks)}\n")

# people named in yours 1 (capitalised two-word names) repeated across pours
out.append("\n## Proper names repeated across readings (two-word capitalised, in yours)\n")
nm = defaultdict(set)
STOP = {"The", "In", "So", "But", "And", "When", "If", "It", "He", "She", "They", "I", "A", "On", "At", "By", "For", "New", "Old"}
for k, r in m.items():
    for a, b in re.findall(r"\b([A-Z][a-zé]+) ([A-Z][a-zé]+)\b", " ".join(r["yours"])):
        if a not in STOP:
            nm[f"{a} {b}"].add(k)
for n_, ks in sorted(nm.items(), key=lambda x: -len(x[1])):
    if len(ks) > 1:
        out.append(f"- {n_} ×{len(ks)}: {', '.join(sorted(ks))}\n")

# recipe neighbours above threshold
out.append("\n## Closest recipe neighbours (cosine ≥ 0.80 on ingredients, family and style)\n")
seen = set()
for k, r in sorted(m.items()):
    for j, s in r["neighbours"]:
        if s >= 0.80 and frozenset((k, j)) not in seen:
            seen.add(frozenset((k, j)))
            out.append(f"- {s}: {k} *{r['name']}* ({r['family']}/{r['style']}) ↔ {j} *{m[j]['name']}* ({m[j]['family']}/{m[j]['style']})\n")

# reversed pairs sharing family+style or base
out.append("\n## Reversed pairs that share Codex family and style\n")
done = set()
for k, r in sorted(m.items()):
    rk = f"{r['secondary']}-{r['primary']}"
    if rk in m and frozenset((k, rk)) not in done:
        done.add(frozenset((k, rk)))
        q = m[rk]
        b1 = r["ingredients"][0]["key"] if r["ingredients"] else ""
        b2 = q["ingredients"][0]["key"] if q["ingredients"] else ""
        same = (r["family"], r["style"]) == (q["family"], q["style"])
        if same or b1 == b2:
            out.append(f"- {k} *{r['name']}* / {rk} *{q['name']}*: {r['family']}/{r['style']} vs {q['family']}/{q['style']}; first ingredient {b1} vs {b2}\n")

# balance and contains summaries
out.append("\n## Balance verdicts (live balance.py)\n")
for v in ("OUT OF RANGE", "freeform"):
    ks = [k for k, r in sorted(m.items()) if r["balance"].get("verdict", "").startswith(v)]
    out.append(f"- **{v}** ({len(ks)}): {', '.join(ks)}\n")
out.append("\n## contains: pour file vs live allergens.py\n")
for k, r in sorted(m.items()):
    f = re.sub(r"[`\s]", "", r["contains_file"]).split("(")[0]
    try:
        f = sorted(json.loads(f))
    except Exception:
        pass
    t = r["contains_tool"]
    if f != (sorted(t) if isinstance(t, list) else t):
        out.append(f"- **{k}** ({r['status'].split()[0]}): file {r['contains_file']} · tool {t}\n")
vf = [k for k, r in m.items() if r["contains_tool"] == []]
out.append(f"\nVeto-free by the live tool: {len(vf)} of {len(m)}; approved and veto-free: {sum(1 for k in vf if m[k]['status'].startswith('approved'))}.\n")

# history share proxy and lengths
out.append("\n## Reading length (words in yours)\n")
ws = sorted((r["reading_words"], k) for k, r in m.items())
out.append(f"- shortest: {', '.join(f'{k} {w}' for w, k in ws[:5])}\n- longest: {', '.join(f'{k} {w}' for w, k in ws[-8:])}\n")
wy = sorted((len(re.findall(r'\w+', r['whoYouAre'])), k) for k, r in m.items())
out.append(f"- whoYouAre longest: {', '.join(f'{k} {w}' for w, k in wy[-8:])}\n")

(REVIEW / "signals.md").write_text("".join(out))
print("ok")
